export const AVIANCA_BAGGAGE_SERVICE_LIST_DEFINTIIONS = {
  SRV1: {
    ServiceDefinitionID: "SRV1",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV2: {
    ServiceDefinitionID: "SRV2",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV3: {
    ServiceDefinitionID: "SRV3",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV4: {
    ServiceDefinitionID: "SRV4",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV5: {
    ServiceDefinitionID: "SRV5",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV6: {
    ServiceDefinitionID: "SRV6",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV7: {
    ServiceDefinitionID: "SRV7",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV8: {
    ServiceDefinitionID: "SRV8",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV9: {
    ServiceDefinitionID: "SRV9",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV10: {
    ServiceDefinitionID: "SRV10",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV11: {
    ServiceDefinitionID: "SRV11",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV12: {
    ServiceDefinitionID: "SRV12",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV13: {
    ServiceDefinitionID: "SRV13",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV14: {
    ServiceDefinitionID: "SRV14",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV15: {
    ServiceDefinitionID: "SRV15",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV16: {
    ServiceDefinitionID: "SRV16",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV17: {
    ServiceDefinitionID: "SRV17",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV18: {
    ServiceDefinitionID: "SRV18",
    OwnerCode: "AV",
    Name: "1ST CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CC",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "61643865" } },
      { DescID: "6", DescText: "B1" },
    ],
    BookingInstructions: { SSRCode: "ABAG", AddlDataMeasure: "1" },
  },
  SRV19: {
    ServiceDefinitionID: "SRV19",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV20: {
    ServiceDefinitionID: "SRV20",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV21: {
    ServiceDefinitionID: "SRV21",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV22: {
    ServiceDefinitionID: "SRV22",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV23: {
    ServiceDefinitionID: "SRV23",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV24: {
    ServiceDefinitionID: "SRV24",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "68686348" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV25: {
    ServiceDefinitionID: "SRV25",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV26: {
    ServiceDefinitionID: "SRV26",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV27: {
    ServiceDefinitionID: "SRV27",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV28: {
    ServiceDefinitionID: "SRV28",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV29: {
    ServiceDefinitionID: "SRV29",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV30: {
    ServiceDefinitionID: "SRV30",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "68686348" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV31: {
    ServiceDefinitionID: "SRV31",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV32: {
    ServiceDefinitionID: "SRV32",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV33: {
    ServiceDefinitionID: "SRV33",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV34: {
    ServiceDefinitionID: "SRV34",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV35: {
    ServiceDefinitionID: "SRV35",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "65645383" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV36: {
    ServiceDefinitionID: "SRV36",
    OwnerCode: "AV",
    Name: "2ND CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CD",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "68686348" } },
      { DescID: "6", DescText: "B2" },
    ],
    BookingInstructions: { SSRCode: "BBAG", AddlDataMeasure: "1" },
  },
  SRV37: {
    ServiceDefinitionID: "SRV37",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV38: {
    ServiceDefinitionID: "SRV38",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV39: {
    ServiceDefinitionID: "SRV39",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV40: {
    ServiceDefinitionID: "SRV40",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV41: {
    ServiceDefinitionID: "SRV41",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV42: {
    ServiceDefinitionID: "SRV42",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV43: {
    ServiceDefinitionID: "SRV43",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV44: {
    ServiceDefinitionID: "SRV44",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV45: {
    ServiceDefinitionID: "SRV45",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV46: {
    ServiceDefinitionID: "SRV46",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV47: {
    ServiceDefinitionID: "SRV47",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV48: {
    ServiceDefinitionID: "SRV48",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV49: {
    ServiceDefinitionID: "SRV49",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV50: {
    ServiceDefinitionID: "SRV50",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV51: {
    ServiceDefinitionID: "SRV51",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV52: {
    ServiceDefinitionID: "SRV52",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV53: {
    ServiceDefinitionID: "SRV53",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV54: {
    ServiceDefinitionID: "SRV54",
    OwnerCode: "AV",
    Name: "3RD CHECKED BAG 23KG 158 LCM",
    ReasonForIssuanceCode: "C",
    ReasonForIssuanceSubCode: "0CE",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", Media: { MediaID: "90425984" } },
      { DescID: "6", DescText: "B3" },
    ],
    BookingInstructions: { SSRCode: "CBAG", AddlDataMeasure: "1" },
  },
  SRV73: {
    ServiceDefinitionID: "SRV73",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV74: {
    ServiceDefinitionID: "SRV74",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV75: {
    ServiceDefinitionID: "SRV75",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV76: {
    ServiceDefinitionID: "SRV76",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV77: {
    ServiceDefinitionID: "SRV77",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV78: {
    ServiceDefinitionID: "SRV78",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV79: {
    ServiceDefinitionID: "SRV79",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV80: {
    ServiceDefinitionID: "SRV80",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV81: {
    ServiceDefinitionID: "SRV81",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV82: {
    ServiceDefinitionID: "SRV82",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV83: {
    ServiceDefinitionID: "SRV83",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV84: {
    ServiceDefinitionID: "SRV84",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV85: {
    ServiceDefinitionID: "SRV85",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV86: {
    ServiceDefinitionID: "SRV86",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV87: {
    ServiceDefinitionID: "SRV87",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV88: {
    ServiceDefinitionID: "SRV88",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV89: {
    ServiceDefinitionID: "SRV89",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
  SRV90: {
    ServiceDefinitionID: "SRV90",
    OwnerCode: "AV",
    Name: "CARRY ON BAGGAGE 10KG 115 LCM",
    ReasonForIssuanceCode: "E",
    ReasonForIssuanceSubCode: "010",
    ValidatingCarrierCode: "AV",
    Description: [
      { DescID: "1", DescText: "Chargeable" },
      { DescID: "2", DescText: "F" },
      { DescID: "3", DescText: "01" },
      { DescID: "4", DescText: "BG" },
      { DescID: "5", DescText: "CY" },
      { DescID: "6", DescText: "10" },
      { DescID: "7", DescText: "5C" },
    ],
    BookingInstructions: { SSRCode: "CABG", AddlDataMeasure: "1" },
  },
};